# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: flask CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Create virtual environment
      run: | 
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
            python -m pip install --upgrade pip
            python -m pip install -r requirements.txt
    
    - name: Print debugging info
      run: |
        echo "Python version: $(python --version)"
        echo "Working directory: $(pwd)"
        echo "Files in the directory: $(ls -la)"
        echo "Contents of site-packages: $(ls -l venv/lib/python*/site-packages)"

    - name: Run tests
      run: python routes.py

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USER }}/flask-app:latest